### ISSUE TITLE
No map files built

### ISSUE THREAD

**Issue by marcelkorpel** [eddyerburgh/parcel-vuejs-template#6]
After running the exact commands stated in the Readme file, a correct application is build using Parcel. However, there are no map files in my `dist` directory. What is wrong with my setup?

**Comment by eddyerburgh** [comment]
Source maps are only generated for the dev build. Are you having problems with the dev script, or would you like to see source maps for the production build?

**Comment by marcelkorpel** [comment]
No, I did run `npm run dev`, but no source maps showed up, and the browser did not show any source files. AFAIK, Parcel also outputs files to `dist` when creating a dev build.

**Comment by eddyerburgh** [comment]
Can you try again. It should now generate a map
